var products = [
  {
    id: "PR-101",
    title: "Bleu de Chanel EDP",
    brand: "Chanel",
    price: 5890000,
    image: "https://images.unsplash.com/photo-1773527142301-9aa77252e5c2?w=600&h=600&fit=crop&q=80",
    description: "بلو دو شنل ادو پرفیوم یک عطر مردانه با رایحه‌ای چوبی-آروماتیک است. ترکیبی بی‌نظیر از نت‌های مرکباتی تازه، چوب صندل و عنبر.",
    volume: "100ml",
    fragranceNotes: "نت‌های سر: گریپ‌فروت، لیمو، نعناع | نت‌های میانی: زنجبیل، فلفل صورتی، یاس | نت‌های پایه: چوب صندل، سدر، عنبر",
    season: "پاییز و زمستان",
    longevity: "۸ تا ۱۰ ساعت",
    sillage: "متوسط تا بالا",
    category: "مردانه"
  },
  {
    id: "PR-102",
    title: "Sauvage Elixir",
    brand: "Dior",
    price: 6450000,
    image: "https://images.unsplash.com/photo-1774682060910-ba9a26f958ad?w=600&h=600&fit=crop&q=80",
    description: "سواواج الکسیر یک عطر مردانه فوق‌العاده جذاب و قدرتمند از برند دیور است. ترکیبی از ادویه‌ها، چوب‌ها و عناصر تاریک.",
    volume: "60ml",
    fragranceNotes: "نت‌های سر: دارچین، جوز هندی | نت‌های میانی: اسطوخودوس، شبت | نت‌های پایه: شیرین‌بیان، چوب صندل، عنبر",
    season: "پاییز و زمستان",
    longevity: "۱۰ تا ۱۲ ساعت",
    sillage: "بسیار بالا",
    category: "مردانه"
  },
  {
    id: "PR-103",
    title: "Black Opium EDP",
    brand: "Yves Saint Laurent",
    price: 4750000,
    image: "https://images.unsplash.com/photo-1771990770592-2fea44c43617?w=600&h=600&fit=crop&q=80",
    description: "بلک اوپیوم یک عطر زنانه اعتیادآور و جذاب. ترکیبی از قهوه سیاه، وانیل و گل‌های سفید.",
    volume: "90ml",
    fragranceNotes: "نت‌های سر: فلفل صورتی، گلابی، پرتقال | نت‌های میانی: قهوه، یاسمن، بادام | نت‌های پایه: وانیل، چوب سدر، کهربا",
    season: "پاییز و زمستان",
    longevity: "۷ تا ۹ ساعت",
    sillage: "متوسط تا بالا",
    category: "زنانه"
  },
  {
    id: "PR-104",
    title: "Acqua di Gio Profondo",
    brand: "Giorgio Armani",
    price: 5200000,
    image: "https://images.unsplash.com/photo-1739190940453-20900e9d18fb?w=600&h=600&fit=crop&q=80",
    description: "آکوا دی جیو پروفوندو یک عطر مردانه دریایی و تازه. با الهام از عمق اقیانوس.",
    volume: "125ml",
    fragranceNotes: "نت‌های سر: مرنیت، پرتقال، لیمو | نت‌های میانی: اسطوخودوس، سرو کوهی | نت‌های پایه: چوب سدر، مشک، کهربا",
    season: "بهار و تابستان",
    longevity: "۶ تا ۸ ساعت",
    sillage: "متوسط",
    category: "مردانه"
  },
  {
    id: "PR-105",
    title: "La Vie Est Belle Intensé",
    brand: "Lancôme",
    price: 5100000,
    image: "https://images.unsplash.com/photo-1760920248537-c1185bbc5c61?w=600&h=600&fit=crop&q=80",
    description: "لا ویه است بل اینتنس یک عطر زنانه شاد و پرانرژی با رایحه‌ای گلی، میوه‌ای و وانیلی.",
    volume: "75ml",
    fragranceNotes: "نت‌های سر: تمشک، گلابی، پرتقال | نت‌های میانی: یاسمن، زنبق | نت‌های پایه: وانیل، پرالین، دانه تونکا",
    season: "بهار و تابستان",
    longevity: "۸ تا ۱۰ ساعت",
    sillage: "بالا",
    category: "زنانه"
  },
  {
    id: "PR-106",
    title: "Oud Wood EDP",
    brand: "Tom Ford",
    price: 8900000,
    image: "https://images.unsplash.com/photo-1759793499819-bf60128a54b4?w=600&h=600&fit=crop&q=80",
    description: "اود وود یک عطر یونیسکس لوکس و خاص. ترکیبی منحصربه‌فرد از چوب عود، وانیل و ادویه‌ها.",
    volume: "100ml",
    fragranceNotes: "نت‌های سر: فلفل برزیلی، رزماری | نت‌های میانی: چوب عود، چوب صندل | نت‌های پایه: وانیل، مشک، کهربا",
    season: "پاییز و زمستان",
    longevity: "۱۰ تا ۱۲ ساعت",
    sillage: "متوسط تا بالا",
    category: "یونیسکس"
  },
  {
    id: "PR-107",
    title: "Light Blue EDP Intense",
    brand: "Dolce & Gabbana",
    price: 4350000,
    image: "https://images.unsplash.com/photo-1770301410072-f6ef6dad65b2?w=600&h=600&fit=crop&q=80",
    description: "لایت بلو اینتنس یک عطر زنانه تازه و مدیترانه‌ای. با الهام از سواحل آفتابی ایتالیا.",
    volume: "65ml",
    fragranceNotes: "نت‌های سر: سیب سبز، لیمو، یخ | نت‌های میانی: یاسمن، گل رز | نت‌های پایه: چوب سدر، مشک، کهربا",
    season: "بهار و تابستان",
    longevity: "۶ تا ۸ ساعت",
    sillage: "متوسط",
    category: "زنانه"
  },
  {
    id: "PR-108",
    title: "1 Million Parfum",
    brand: "Paco Rabanne",
    price: 5650000,
    image: "https://images.unsplash.com/photo-1768025719875-48ed072f3084?w=600&h=600&fit=crop&q=80",
    description: "وان میلیون پارفوم یک عطر مردانه لوکس و خیره‌کننده. نمادی از موفقیت و قدرت.",
    volume: "100ml",
    fragranceNotes: "نت‌های سر: ترون، گریپ‌فروت، نعناع | نت‌های میانی: رز، دارچین | نت‌های پایه: چوب پچولی، عنبر، چرم",
    season: "پاییز و زمستان",
    longevity: "۱۰ تا ۱۲ ساعت",
    sillage: "بسیار بالا",
    category: "مردانه"
  }
];
